### ISSUE TITLE
error depends with rails 5.1.1

### ISSUE THREAD

**Issue by denegny** [apiqcms/kms#16]
Use bundle

```
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.1.1)

    kms was resolved to 0.9.0, which depends on
      rails (~> 5.0.0)
```

**Comment by GarPit** [comment]
Hello.

Thanks for reporting. Yes, at this moment Rails 5.0 supported, but this milestone will include Rails 5.1 support.

**Comment by GarPit** [comment]
@denegny, you could try master branch, dependency was updated
