### ISSUE TITLE
Any guideline to set I18N for front-end?

### ISSUE THREAD

**Issue by AbelLai** [apiqcms/kms#33]
Hi,

Right now, I know that set the web site language to be Chinese via `config.i18n.default_locale = 'zh-CN'` at the file `/config/application.rb` after I install kms into my rails app. But I cannot find any guideline for the front-end. Is there anyone can help?

Thanks.

**Comment by AbelLai** [comment]
OK, I read the code, and found via `config.i18n.default_locale = 'zh-CN'`, it works for front-end.

Issue closed.

**Comment by GarPit** [comment]
Hello @AbelLai.

Yes, actually you're responsible for frontend, there's no translations approach there

**Comment by GarPit** [comment]
It should work. Did you do assets precompilation for production?

**Comment by AbelLai** [comment]
Yes, I did assets precompilation for production environment.

**Comment by GarPit** [comment]
Hm, then I don't have suggestions, need more information. Maybe you could share your entire project?
