### ISSUE TITLE
Add host to carrierwave fog config

### ISSUE THREAD

**Issue by eldarik** [apiqcms/kms#35]
If you use another cloud storage(like s3), that support s3 api, for example, mailru hotbox(https://mcs.mail.ru/hotbox/) use must add host to carrierwave config.

**Comment by GarPit** [comment]
Hello @eldarik. Yes, only S3 supported at this moment. But actually this could be customized I think in concrete `config/initializers/carrierwave.rb` (after APIQ installed). Maybe you want to add this config option?

**Comment by eldarik** [comment]
@GarPit Yes, I've already set fog credentials:
```
    config.fog_credentials = {
      provider:                           'AWS',
      aws_access_key_id:         ENV['AWS_ACCESS_KEY_ID'],
      aws_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      region:                              ENV['AWS_REGION'] || 'us-east-1',
      host:                                 ENV['AWS_HOST'],
      endpoint:                          ENV['AWS_ENDPOINT']
    }
```
Maybe, this information could be useful for other?

**Comment by GarPit** [comment]
@eldarik Yes, makes sense. I think I'll add this to README. Thanks!
